extends:
  - recommended/esnext
  - recommended/esnext/style-guide
  - recommended/node
  - recommended/node/style-guide

env:
  node: true

parserOptions:
  ecmaVersion: 2017

rules:
  "import/no-commonjs": off
  "import/newline-after-import": off
  indent:
    - error
    - 2
    - SwitchCase: 1
  comma-dangle: off
  semi: error
  curly:
    - error
    - all
  eol-last: error
  no-else-return: off
